export const ACCOMMODATION_RESEARCH_DOC_ID = "summer-2027";

export const ACCOMMODATION_STATUS_OPTIONS = [
  "À contacter",
  "Contacté",
  "À relancer",
  "Visite prévue",
  "Devis reçu",
  "Refusé / indisponible",
];

export const ACCOMMODATION_FIT_OPTIONS = ["Conforme", "À confirmer", "Hors critère"];

export const ACCOMMODATION_SEED = [
  {
    id: "ocean-bi-izarrak",
    type: "ocean",
    priority: 1,
    department: "64",
    name: "Bi-Izarrak – Izarperdia / Ithurbidia",
    location: "Bidart",
    access: "Environ 800 m de la plage",
    capacity: "56 lits à Izarperdia ; jusqu’à 150 sur les deux centres",
    selfCatering: "Oui",
    fit: "Conforme",
    phone: "05 59 47 42 16 / 06 51 20 09 98",
    email: "barbierl@bi-izarrak.com",
    website: "https://www.izarperdia.fr/",
    status: "Contacté",
    source: "https://bi-izarrak.com/wp-content/uploads/2017/11/Plaquetteasso2018web.pdf",
    notes: "Gestion libre confirmée. Hébergeur ColoCrew 2025 et contact déjà chaud. À demander en priorité pour juillet 2027.",
  },
  {
    id: "ocean-vent-est",
    type: "ocean",
    priority: 1,
    department: "33",
    name: "Vent d’Est",
    location: "Vendays-Montalivet",
    access: "500 à 800 m de l’océan",
    capacity: "Gîtes de 20 ou 36 lits ; chalets de 14 lits",
    selfCatering: "Oui",
    fit: "Conforme",
    phone: "05 56 73 76 41 / 06 73 27 81 14",
    email: "contact@ventdest.net",
    website: "https://www.ventdest.net/",
    status: "À relancer",
    source: "https://www.ventdest.net/",
    notes: "Gestion libre affichée, groupes et colonies acceptés, modules adaptés à 30–40 personnes. Contact ancien sans réponse.",
  },
  {
    id: "ocean-pins-bleus",
    type: "ocean",
    priority: 1,
    department: "40",
    name: "Camping municipal Les Pins Bleus",
    location: "Labenne Océan",
    access: "Avenue de l’Océan ; plage accessible à pied",
    capacity: "Espace dédié aux groupes, capacité exacte à confirmer",
    selfCatering: "Oui",
    fit: "Conforme",
    phone: "05 59 45 41 13",
    email: "camping@lespinsbleus.com",
    website: "https://www.lespinsbleus.com/nos-emplacements/espace-groupe-equipe/",
    status: "À contacter",
    source: "https://www.lespinsbleus.com/nos-emplacements/espace-groupe-equipe/",
    notes: "Espace groupes/colos avec cuisine équipée, réfrigérateurs, gazinières et lodge couvert. Demander capacité, agrément mineurs et disponibilité été 2027.",
  },
  {
    id: "ocean-abri-cotier",
    type: "ocean",
    priority: 1,
    department: "40",
    name: "L’Abri-Côtier (UMCV)",
    location: "Vieux-Boucau-les-Bains",
    access: "800 m de l’océan ; 100 m du lac marin",
    capacity: "Jusqu’à 250 personnes",
    selfCatering: "Oui",
    fit: "Conforme",
    phone: "05 58 48 03 33 / 07 57 77 18 18",
    email: "umcv81@gmail.com",
    website: "https://www.labri-cotier.fr/gite-de-groupes/",
    status: "À relancer",
    source: "https://www.labri-cotier.fr/gite-de-groupes/",
    notes: "Gestion libre explicitement proposée et déplacements possibles à pied. Même association que Le Boucalais.",
  },
  {
    id: "ocean-pastourelles",
    type: "ocean",
    priority: 2,
    department: "40",
    name: "Les Pastourelles – bâtiment Acacias",
    location: "Capbreton",
    access: "Environ 800 m de la plage",
    capacity: "50 lits, deux niveaux avec cuisines",
    selfCatering: "Oui",
    fit: "Conforme",
    phone: "05 58 72 10 33",
    email: "lespastourelles40@orange.fr",
    website: "",
    status: "Refusé / indisponible",
    source: "Excel transmis",
    notes: "Très bon format en gestion libre, mais indiqué comme indisponible/refusé dans le suivi. À conserver pour une autre période.",
  },
  {
    id: "ocean-vvf-soulac",
    type: "ocean",
    priority: 2,
    department: "33",
    name: "VVF Les Plages du Médoc",
    location: "Soulac-sur-Mer",
    access: "Village au bord de l’océan",
    capacity: "Groupes dès 5 logements ; capacité à chiffrer",
    selfCatering: "Oui, en logements",
    fit: "À confirmer",
    phone: "05 56 09 81 35",
    email: "Formulaire : vvf-groupes.fr",
    website: "https://www.vvf-groupes.fr/hebergements/village-vacances-les-plages-du-medoc.html",
    status: "À contacter",
    source: "https://www.vvf-groupes.fr/hebergements/village-vacances-les-plages-du-medoc.html",
    notes: "Autonomie par logements plutôt qu’une cuisine collective. Vérifier possibilité de privatiser un secteur et accueil ACM.",
  },
  {
    id: "ocean-ocean-shelter",
    type: "ocean",
    priority: 2,
    department: "40",
    name: "Ocean Shelter",
    location: "Seignosse",
    access: "Plage des Casernes à environ 7 min ; trajet à pied à vérifier",
    capacity: "Jusqu’à 50 personnes, 19 chambres/ hébergements",
    selfCatering: "Oui",
    fit: "À confirmer",
    phone: "07 67 49 15 19",
    email: "info@oceanshelter.com",
    website: "https://www.oceanshelter-seignosse.fr/",
    status: "À contacter",
    source: "https://www.seignosse-tourisme.com/content/uploads/2023/03/Seignosse-HEB23-BD.pdf",
    notes: "Site privatisable avec grande cuisine commune. Excellent format groupe ; confirmer le temps réel à pied jusqu’au surf et l’accueil de mineurs.",
  },
  {
    id: "ocean-bella-vista",
    type: "ocean",
    priority: 2,
    department: "64",
    name: "Bella Vista Guest Center (CBE Horizon)",
    location: "Hendaye",
    access: "700 à 900 m de l’océan",
    capacity: "134 couchages sur 3 bâtiments",
    selfCatering: "À confirmer",
    fit: "À confirmer",
    phone: "05 59 70 58 51",
    email: "contact@cbe-horizon.fr",
    website: "https://cbe-horizon.fr/nos-guest-center/bella-vista-hendaye/",
    status: "Contacté",
    source: "https://cbe-horizon.fr/contact/",
    notes: "Ils doivent rappeler. Demander une privatisation de 35 places avec cuisine en autonomie, non confirmée sur le site.",
  },
  {
    id: "ocean-nouvel-horizon",
    type: "ocean",
    priority: 2,
    department: "40",
    name: "Nouvel Horizon Guest Center",
    location: "Vieux-Boucau-les-Bains",
    access: "900 m de l’océan ; 100 m du lac marin",
    capacity: "Groupes, capacité à confirmer",
    selfCatering: "À confirmer",
    fit: "À confirmer",
    phone: "05 59 70 58 51",
    email: "contact@cbe-horizon.fr",
    website: "https://cbe-horizon.fr/",
    status: "À contacter",
    source: "https://cbe-horizon.fr/contact/",
    notes: "Même centrale que Bella Vista : demander les deux sites dans le même échange et exiger une formule sans restauration.",
  },
  {
    id: "ocean-boucalais",
    type: "ocean",
    priority: 2,
    department: "40",
    name: "Le Boucalais Surf Spot",
    location: "Vieux-Boucau-les-Bains",
    access: "Plage et lac accessibles à pied ou à vélo",
    capacity: "115 couchages",
    selfCatering: "À confirmer",
    fit: "À confirmer",
    phone: "05 58 57 85 74",
    email: "infos@alohaspot.fr",
    website: "https://alohaspot.fr/le-boucalais-surf-spot/",
    status: "À relancer",
    source: "https://alohaspot.fr/le-boucalais-surf-spot/",
    notes: "Le site actuel met surtout en avant la restauration. Confirmer qu’une cuisine et une formule gestion libre restent possibles.",
  },
  {
    id: "ocean-mjc-soulac",
    type: "ocean",
    priority: 3,
    department: "33",
    name: "Centre de séjour MJC du Tarn",
    location: "Soulac-sur-Mer",
    access: "150 m de la plage",
    capacity: "60 lits en chambres, extension sous tentes",
    selfCatering: "À confirmer",
    fit: "À confirmer",
    phone: "06 08 24 67 05 / 05 56 09 87 33",
    email: "centremjcsoulac@fdmjc-tarn.fr",
    website: "https://www.mjc81-soulac.fr/sejour-groupes/",
    status: "Refusé / indisponible",
    source: "https://www.mjc81-soulac.fr/sejour-groupes/",
    notes: "Très proche plage mais accueil groupes annoncé surtout en mai-juin et septembre-octobre. Cuisine autonome non confirmée.",
  },
  {
    id: "ocean-cap-ocean",
    type: "ocean",
    priority: 3,
    department: "40",
    name: "Village-Club Cap Océan",
    location: "Seignosse",
    access: "400 à 500 m de la plage des Estagnots",
    capacity: "Secteur groupes ; capacité à confirmer",
    selfCatering: "Non confirmée",
    fit: "Hors critère",
    phone: "05 58 43 31 15 / 05 65 22 68 21",
    email: "reservation.capocean@fol46.org",
    website: "https://www.capocean.org/fr",
    status: "Visite prévue",
    source: "https://www.capocean.org/fr",
    notes: "Excellent emplacement surf, mais offres publiées en pension/demi-pension. Garder la visite pour négocier une cuisine autonome.",
  },
  {
    id: "ocean-littoral-basque",
    type: "ocean",
    priority: 3,
    department: "64",
    name: "Maison du Littoral Basque (PEP64)",
    location: "Socoa / Ciboure",
    access: "200 m de la plage de Socoa",
    capacity: "89 lits, 3 unités d’environ 30",
    selfCatering: "Non confirmée",
    fit: "Hors critère",
    phone: "05 59 47 04 14",
    email: "centre-pep-socoa@pep64.org",
    website: "https://www.pep64.org/",
    status: "À relancer",
    source: "Excel transmis",
    notes: "Très bon découpage de capacité mais formule pension indiquée. À réactiver uniquement si la gestion libre est possible.",
  },
  {
    id: "ocean-ufoval",
    type: "ocean",
    priority: 3,
    department: "64",
    name: "Centre UFOVAL (FOL74)",
    location: "Hendaye",
    access: "Plage annoncée à quelques pas",
    capacity: "Environ 40 enfants",
    selfCatering: "À confirmer",
    fit: "À confirmer",
    phone: "04 50 52 30 00",
    email: "vacances@fol74.org",
    website: "https://ufoval.fol74.org/",
    status: "Contacté",
    source: "Excel transmis",
    notes: "Mail déjà envoyé. Confirmer l’adresse exacte, la cuisine autonome et l’ouverture à un organisateur extérieur en été 2027.",
  },
  {
    id: "ocean-evasoleil",
    type: "ocean",
    priority: 3,
    department: "33",
    name: "Centre Evasoleil",
    location: "Vendays-Montalivet",
    access: "Environ 15 min à pied de la plage nord",
    capacity: "Centre de vacances, capacité à confirmer",
    selfCatering: "À confirmer",
    fit: "À confirmer",
    phone: "06 62 81 20 00",
    email: "info@evasoleil.com",
    website: "https://www.colonie-evasoleil.com/",
    status: "À contacter",
    source: "https://www.vendays-montalivet-tourisme.fr/app/uploads/vendaysmontalivet/2025/03/VENDAYS-GUIDEPRATIQUE-2025.pdf",
    notes: "Centre exploité par un organisateur de colonies. Vérifier s’ils louent réellement le site et la cuisine à une association tierce.",
  },
  {
    id: "ocean-pignadar",
    type: "ocean",
    priority: 3,
    department: "40",
    name: "Le Pignadar",
    location: "Vieux-Boucau-les-Bains",
    access: "Environ 15 min à pied de l’océan",
    capacity: "Groupes d’enfants et familles ; capacité à confirmer",
    selfCatering: "Non",
    fit: "Hors critère",
    phone: "06 82 77 14 04 / 06 82 77 14 05",
    email: "famille-nature-et-progres@orange.fr",
    website: "https://famillenatureprogres.wixsite.com/le-pignadar",
    status: "À contacter",
    source: "https://famillenatureprogres.wixsite.com/le-pignadar",
    notes: "Restauration sur place uniquement annoncée. À écarter si aucune dérogation de gestion libre n’est possible.",
  },
  {
    id: "ocean-ispe-larrigade",
    type: "ocean",
    priority: 3,
    department: "40",
    name: "Centre Ispe Larrigade",
    location: "Biscarrosse Lac",
    access: "6 km des premières plages océanes",
    capacity: "26 chalets de 7 lits",
    selfCatering: "Oui",
    fit: "Hors critère",
    phone: "05 58 09 82 99",
    email: "ispe@laligue47.org",
    website: "https://ispelarrigade-biscarrosse.fr/",
    status: "À contacter",
    source: "https://ispelarrigade-biscarrosse.fr/",
    notes: "Très bon équipement en gestion libre, mais l’océan n’est pas accessible à pied. Utile seulement avec minibus ou surf au lac.",
  },
  {
    id: "river-soeix",
    type: "river",
    priority: 1,
    department: "64",
    name: "Gîte du Centre Nautique de Soeix",
    location: "Oloron-Sainte-Marie",
    access: "Au bord du gave d’Aspe ; activités eau vive sur place",
    capacity: "29 à 30 couchages",
    selfCatering: "Oui",
    fit: "Conforme",
    phone: "06 08 22 13 28 / 05 59 39 61 00",
    email: "basesoeix@free.fr",
    website: "https://raft-oloron.com/pension-complete-hebergement/",
    status: "À contacter",
    source: "https://www.gites-de-france.com/fr/nouvelle-aquitaine/pyrenees-atlantiques/soeix-64g522001",
    notes: "Meilleure adéquation : gîte entier, cuisine équipée pour 30 et rafting/hydrospeed/kayak directement sur place.",
  },
  {
    id: "river-gites-aure",
    type: "river",
    priority: 1,
    department: "65",
    name: "Les Gîtes d’Aure",
    location: "Vielle-Aure / Saint-Lary",
    access: "Vallée de la Neste ; bases de rafting de Saint-Lary à proximité",
    capacity: "40 couchages dans deux gîtes réunis",
    selfCatering: "Oui",
    fit: "Conforme",
    phone: "06 30 37 22 81 / 06 17 52 11 21",
    email: "Formulaire : gitesdaure.fr/?page_id=10",
    website: "https://gitesdaure.fr/",
    status: "À contacter",
    source: "https://gitesdaure.fr/",
    notes: "Privatisation entière, 15 chambres et cuisine industrielle. E-mail public non affiché : premier contact par formulaire ou téléphone.",
  },
  {
    id: "river-barane",
    type: "river",
    priority: 1,
    department: "09",
    name: "Gîte Barané",
    location: "Gabre, Ariège",
    access: "Environ 35–45 min des parcours rafting de Foix",
    capacity: "27 à 35 couchages",
    selfCatering: "Oui",
    fit: "Conforme",
    phone: "06 33 71 73 29",
    email: "reservations@gitebarane.fr",
    website: "https://gitebarane.fr/",
    status: "À contacter",
    source: "https://gitebarane.fr/",
    notes: "Gestion libre et location entière confirmées. Bon format 30–35 ; trajet activité plus long que Soeix ou Isaby.",
  },
  {
    id: "river-arignac",
    type: "river",
    priority: 1,
    department: "09",
    name: "Domaine d’Arignac",
    location: "Arignac / Tarascon-sur-Ariège",
    access: "Près de l’Ariège et des prestataires eau vive de Foix/Tarascon",
    capacity: "40 couchages, 11 chambres",
    selfCatering: "Oui",
    fit: "Conforme",
    phone: "06 33 81 49 62 / 06 84 99 09 48",
    email: "Contact via domaine-arignac.com",
    website: "https://www.domaine-arignac.com/",
    status: "À contacter",
    source: "https://www.gites-de-france-ariege.com/location-Gites-etape-sejour-Arignac-Ariege-09G4007.html",
    notes: "Domaine privatisable en gestion libre avec cuisine professionnelle. Faire confirmer l’adresse e-mail et les agréments ACM.",
  },
  {
    id: "river-relais-isaby",
    type: "river",
    priority: 2,
    department: "65",
    name: "Le Relais d’Isaby",
    location: "Villelongue / Argelès-Gazost",
    access: "Embarquement eau vive sur place, au bord du gave de Pau",
    capacity: "48 lits agréés, 50 au total",
    selfCatering: "Oui",
    fit: "Conforme",
    phone: "05 62 92 20 77 / 06 79 75 51 48",
    email: "isaby65@gmail.com",
    website: "https://www.hebergement-groupe-pyrenees.com/",
    status: "À contacter",
    source: "https://www.hebergement-groupe-pyrenees.com/hebergement",
    notes: "Un peu plus grand que la cible, mais cuisine professionnelle, gestion libre, agréments et eau vive directement sur place.",
  },
  {
    id: "river-lustou",
    type: "river",
    priority: 2,
    department: "65",
    name: "Gîte de groupe Le Lustou",
    location: "Vielle-Aure / Saint-Lary",
    access: "À proximité de la Neste et des bases rafting de Saint-Lary",
    capacity: "29 couchages",
    selfCatering: "Oui",
    fit: "À confirmer",
    phone: "05 62 39 40 64",
    email: "contact@lustou.com",
    website: "https://www.lustou.com/gite-groupe-saint-lary/",
    status: "À contacter",
    source: "https://www.lustou.com/wp-content/uploads/2025/03/Brochure_Presentation_Gite_Le_Lustou_VielleAure.pdf",
    notes: "Gestion libre et cuisine équipée confirmées. Il manque un couchage pour 30 : demander ajout de couchages ou mobil-home complémentaire.",
  },
  {
    id: "river-mfr-mane",
    type: "river",
    priority: 2,
    department: "31",
    name: "MFR de Mane",
    location: "Mane / piémont pyrénéen",
    access: "Activités canoë, kayak et rafting annoncées à proximité",
    capacity: "50 à 56 couchages",
    selfCatering: "Oui",
    fit: "À confirmer",
    phone: "05 61 90 50 84",
    email: "mfr.mane@mfr.asso.fr",
    website: "https://www.mfr.fr/locations/",
    status: "À contacter",
    source: "https://www.mfr.fr/locations/",
    notes: "Cuisine de collectivité et gestion libre. Plus grand que la cible ; vérifier privatisation à 30–40 et distance du prestataire eau vive.",
  },
];
