export const DASHBOARD_NAMESPACE = process.env.NEXT_PUBLIC_DASHBOARD_NAMESPACE || "draft";

export const DASHBOARD_COLLECTIONS = {
  SEJOURS: `${DASHBOARD_NAMESPACE}_sejours`,
  PAGES: `${DASHBOARD_NAMESPACE}_pages`,
  BLOG: `${DASHBOARD_NAMESPACE}_blog`,
  TEMOIGNAGES: `${DASHBOARD_NAMESPACE}_temoignages`,
  RESERVATIONS: `${DASHBOARD_NAMESPACE}_reservations`,
};
