export const COLLECTIONS = {
  SEJOURS: "sejours",
  RESERVATIONS: "reservations",
  FINANCE_SUMMARIES: "finance_summaries",
  ACCOUNTING_REPORTS: "accounting_reports",
  TRANSPORTS: "transports",
  TRANSPORT_RDV_POINTS: "transport_rdv_points",
  TRANSPORT_SETTINGS: "transport_settings",
  STAFF_MEMBERS: "staff_members",
  STAFF_CONTRACTS: "staff_contracts",
  STAFF_DOCUMENTS: "staff_documents",
  STAFF_PUBLIC_PROFILES: "staff_public_profiles",
  DAY_PLANS: "day_plans",
  SALARY_GRID: "salary_grid",
  PAGES: "pages",
  BLOG: "blog",
  TEMOIGNAGES: "temoignages",
  MEDIAS: "medias",
  ADMINS: "admins",
  PHOTOS: "photos",
  ALBUMS: "albums",
};
