export const COLLECTIONS = {
  SEJOURS: "sejours",
  RESERVATIONS: "reservations",
  FINANCE_SUMMARIES: "finance_summaries",
  TRANSPORTS: "transports",
  TRANSPORT_RDV_POINTS: "transport_rdv_points",
  STAFF_MEMBERS: "staff_members",
  STAFF_CONTRACTS: "staff_contracts",
  PAGES: "pages",
  BLOG: "blog",
  TEMOIGNAGES: "temoignages",
  MEDIAS: "medias",
  ADMINS: "admins",
  PHOTOS: "photos",
  ALBUMS: "albums",
};
